

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import Header from "@/components/shared/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        
        <AuthProvider><Header/>{children}</AuthProvider>
=======
        <Navbar></Navbar>
        <AuthProvider>{children}</AuthProvider>
>>>>>>> ab00e79a68fdb5e698ce2d4daf41fa60254d298c

        <ToastContainer position="top-right" autoClose={3000} theme="colored" />
        <Footer></Footer>
      </body>
    </html>
  );
}
